services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: http://localhost:3000
        NEXT_PUBLIC_RAWG_API_KEY: b44ca9ea4b2e43d2b3e5b7aefd8c302c
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    ports:
      - 5173:3000
    depends_on:
      - backend
    tty: true
    env_file:
      - docker.env

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src/backend
      - /usr/src/backend/node_modules
    ports:
      - 3000:3000
    tty: true
    depends_on:
      database:
        condition: service_healthy
    command:
      [
        "sh",
        "-c",
        "npx prisma generate && npx prisma db push --accept-data-loss && npm run start:prod",
      ]
    env_file:
      - docker.env
    environment:
      - JWT_SECRET=supersecret_key_change_me_in_prod

  database:
    image: postgres:17-alpine
    container_name: database
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - docker.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gamer -d gamerchallenge"]
      start_period: 15s
      interval: 15s
      timeout: 5s
      retries: 5

  prismastudio:
    image: timothyjmiller/prisma-studio
    container_name: prismastudio
    restart: unless-stopped
    ports:
      - 5555:5555
    env_file:
      - docker.env
    depends_on:
      database:
        condition: service_healthy
