services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    ports:
      - 5173:5173
    depends_on:
      - backend
    tty: true
    env_file:
      - docker.env

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src/backend
      - /usr/src/backend/node_modules
    ports:
      - 3000:3000
    tty: true
    depends_on:
      database:
        condition: service_healthy
    command: >
      bash -c "
        # 1) Generate the Prisma client
        npx prisma generate &&
        npx prisma migrate deploy &&
        npx prisma db push &&
        npx prisma db seed &&
        npm run start:dev
      "
    env_file:
      - docker.env


  database:
    image: postgres:17-alpine
    container_name: database
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - docker.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gamer -d gamerchallenge"]
      start_period: 15s
      interval: 15s
      timeout: 5s
      retries: 5

  prismastudio:
    image: timothyjmiller/prisma-studio
    container_name: prismastudio
    restart: unless-stopped
    ports:
      - 5555:5555
    env_file:
      - docker.env
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./backend/prisma:/app/prisma
    command: ["prisma", "studio", "--schema=/app/prisma/schema.prisma"]

  caddy:
    image: caddy:2
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend
      - backend

volumes:
  caddy_data:
  caddy_config:
  
  cypress:
    image: cypress/included:13.7.3
    container_name: cypress
    working_dir: /e2e
    volumes:
      - ./:/e2e
    depends_on:
      - frontend
    env_file:
      - ./cypress/.env
    entrypoint: 
      - sh
      - -c
      - |
        npm ci && \
        npx cypress install && \
        npx cypress run